services:
  - type: web
    name: reclaim-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: PORT
        value: 5000
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false

  - type: web
    name: reclaim-dashboard
    env: static
    plan: free
    rootDir: frontend-v2
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: reclaim-api
          property: host
